<a href="https://colab.research.google.com/github/PeriBerba/Numerical-Methods/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its Operation

In [10]:
import numpy as np 
A= np.array([1,2,3]) #THIS IS 1 x 3 ARRAY
A[0]=4
print (A)


[4 2 3]


In [9]:
import numpy as np 
B= np.array([[1,2,3],[4,5,6]]) #THIS IS 2 x 3 ARRAY
B[0,0]=7
print (B)

[[7 2 3]
 [4 5 6]]


In [11]:
import numpy as np 
C= np.array([[1,2,3],[4,5,6],[7,8,9]]) #THIS IS AN EXAMPLE OF SQUARE MATRIX
print (C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
import numpy as np
D= np.full((2,2),7) 
print (D)

[[7 7]
 [7 7]]


In [15]:
import numpy as np
E= np.eye(2)
print (E)

[[1. 0.]
 [0. 1.]]


In [16]:
import numpy as np
E= np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print (E)

[1 5 9]


In [17]:
import numpy as np
F= np.empty ((0,10))
print (F)

[]


In [18]:
import numpy as np
G= np.zeros((2,2))
print (G)

[[0. 0.]
 [0. 0.]]


In [24]:
import numpy as np
E= np.eye(2)
G= np.zeros((2,2))
print (E)
print (G)
print (E+G)#this is the code to get the summation of matrices E and G
print (E-G)#this is the code to get the difference of matrices E and G
print (G-E)

[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[-1.  0.]
 [ 0. -1.]]
