<a href="https://colab.research.google.com/github/PeriBerba/Numerical-Methods/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prelim Exam

Peri Julian L. Berba

201911370



In [1]:
import numpy as np
A= np.array([[1,2,3],[2,3,3],[3,4,-2]])
print (A)
print (np.linalg.det(A))
print (round(np.linalg.det(A)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5
