<a href="https://colab.research.google.com/github/PeriBerba/Numerical-Methods/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations


PERI JULIAN BERBA




201911370


#Addition


In [19]:
import numpy as np
A = np.array([
    [-5,0],
    [4,1],
])
B = np.array([
    [6,-3],
    [2,3],
])
print (A+B)

[[ 1 -3]
 [ 6  4]]


#Subtraction


In [21]:
import numpy as np
B = np.array([
    [6,-3],
    [2,3],
])
A = np.array([
    [-5,0],
    [4,1],
])
print (B-A)

[[11 -3]
 [-2  2]]


In [20]:
import numpy as np
A = np.array([
    [-5,0],
    [4,1],
])
B = np.array([
    [6,-3],
    [2,3],
])
print (A-B)

[[-11   3]
 [  2  -2]]
